### ISSUE TITLE
Default output policy

### ISSUE THREAD

**Issue by bobertlo** [void-ansible-roles/network#5]
When setting up "real" systems I do always create static network configuration in a host_vars file, but when setting up test lxc systems, I've found myself "breaking" them and having to log in manually to change the policy, reload the iptables. I think this may be a problem if we are putting the roles onto ansible galaxy. I propose one of the following solutions:

1. Change the default output policy to ACCEPT (it is simple enough for an end user to change it site-wide to tighten security by default.)
2. Document this clearly.

**Comment by the-maldridge** [comment]
I believe a more correct solution here would be for you to add a group_vars/all.yml file in order to across the board weaken the security of your test environment.

**Comment by bobertlo** [comment]
Right, that's what I did for my disposable container lab. I would hope anyone using these reads the Readme, and I see now it is clearly stated in this repo. I worry a small amount about other roles pulling this one in, but I don't see a good answer to that.

**Comment by the-maldridge** [comment]
I have confidence that a professional consumer using Ansible would know to RTFM.  In the case that they don't, well they'll have an interesting time reading source code to find out why the firewall was turned on.

Its my personal philosophy that any admin that blindly runs code from the internet as root without understanding what it does deserves whatever happens next, so the stance for this project will continue to be secure by default.
